# word2vec

**Importing libraries**

In [4]:
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity
from numpy import dot
from numpy.linalg import norm

In [5]:
import gensim.downloader as api
model = api.load('word2vec-google-news-300')

**Loading model**

In [27]:
#model = KeyedVectors.load_word2vec_format('/home/juanluis/projects/embeddings/GoogleNews-vectors-negative300.bin',binary=True)

In [28]:
model

**queen=king-man+woman**

In [29]:
model.most_similar(positive=['woman', 'king'], negative=['man'])

[('queen', 0.7118192911148071),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.549946129322052),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411999702454)]

**princess=prince-man+woman**

In [30]:
model.most_similar(positive=['woman', 'prince'], negative=['man'])

[('princess', 0.7041178941726685),
 ('duchess', 0.6229751110076904),
 ('monarch', 0.6019775867462158),
 ('Queen_Consort', 0.5901833772659302),
 ('queen', 0.5848377346992493),
 ('Camilla', 0.5800651907920837),
 ('Princess', 0.5763431787490845),
 ('princes', 0.5672137141227722),
 ('Princess_Sikhanyiso', 0.5632773041725159),
 ('marrying_commoner', 0.561651349067688)]

Calculating **queen=king-man+woman**

In [32]:
queen_vector = model['queen']
king_vector= model['king']
man_vector = model['man']
woman_vector = model['woman']
result_vector = king_vector-man_vector+woman_vector
cosine_similarity([result_vector],[queen_vector])

array([[0.73005176]], dtype=float32)

**Example (Conference)**

In [34]:
puebla_vector = model['Puebla']
guadalajara_vector = model['Guadalajara']
bicycle_vector = model['bicycle']

In [35]:
cosine_similarity([puebla_vector],[guadalajara_vector])

array([[0.5695188]], dtype=float32)

In [36]:
cosine_similarity([puebla_vector],[bicycle_vector])

array([[0.03059067]], dtype=float32)